/*	Copyright 2007  Edwin Stang (edwinstang@gmail.com), 
                    Kovacs Zsolt (kovacs.zsolt.85@gmail.com)

    This file is part of CoopNet.

    CoopNet is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    CoopNet is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with CoopNet.  If not, see <http://www.gnu.org/licenses/>.
*/

package coopnetclient.panels;

import coopnetclient.frames.BugReport;

public class ErrorPanel extends javax.swing.JPanel {

    public static final int UNKNOWN_MODE = 0;
    public static final int CONNECTION_REFUSED_MODE = 1;
    public static final int CONNECTION_RESET_MODE = 2;
    public static final int UNKNOWN_IO_MODE = 3;
    private int mode;
    private Exception exc;
    private String trafficLog;

    //Message constants
    private final String connectionrefused = "<HTML><p style=\"text-align: center;\"><b>Unable to connect to the server!</b><BR>" +
            "Please make sure you are connected to the internet properly and the server address and port in the settings are correct.<BR>" +
            "If you still cannot connect, the server may be down for maintenance, please try again later.</p> ";
    private final String unknownerror = "<HTML><p style=\"text-align: center;\"><b>An unknown error occured!</b><BR>" +
            "Please help us fix this problem by sending a bug report.</p>";
    private final String connectionreset = "<HTML><p style=\"text-align: center;\"><b>Connection with the server was lost!</b><BR></p>";
    private final String unknownIO = "<HTML><p style=\"text-align: center;\"><b>An unknown IO error occured!</b><BR></p>";
    
    public ErrorPanel(int mode, Exception e) {
        initComponents();
        this.mode = mode;
        this.exc = e;
        this.trafficLog = coopnetclient.TrafficLogger.getEndOfLog();
        
        coopnetclient.coloring.Colorizer.colorize(this);
        switch (mode) {
            case 0: {
                lbl_errortext.setText(unknownerror);
                break;
            }
            case 1: {
                lbl_errortext.setText(connectionrefused);
                btn_report.setVisible(false);
                break;
            }
            case 2: {
                lbl_errortext.setText(connectionreset);
                btn_report.setVisible(false);
                break;
            }
            case 3: {
                lbl_errortext.setText(unknownIO + exc.getMessage());
                btn_report.setVisible(false);
                break;
            }

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_errortext = new javax.swing.JLabel();
        pnl_button = new javax.swing.JPanel();
        btn_report = new javax.swing.JButton();

        lbl_errortext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_errortext.setText("<html><p style=\"text-align: center\"><b>Error header!</b><br>Error description, error description, error description.</p></html>");
        lbl_errortext.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_errortext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_errortext.setIconTextGap(0);
        lbl_errortext.setMaximumSize(new java.awt.Dimension(1000, 1000));
        lbl_errortext.setMinimumSize(new java.awt.Dimension(100, 100));
        lbl_errortext.setName("text"); // NOI18N
        lbl_errortext.setPreferredSize(new java.awt.Dimension(100, 100));

        pnl_button.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 10));

        btn_report.setText("Report this bug");
        btn_report.setAlignmentX(0.5F);
        btn_report.setAlignmentY(0.0F);
        btn_report.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_report.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        pnl_button.add(btn_report);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_errortext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
            .addComponent(pnl_button, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_errortext, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_button, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        new BugReport(exc, trafficLog);
}//GEN-LAST:event_btn_reportActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_report;
    private javax.swing.JLabel lbl_errortext;
    private javax.swing.JPanel pnl_button;
    // End of variables declaration//GEN-END:variables
    
}