/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectingPanel.java
 *
 * Created on 02.01.2009, 17:22:07
 */

package coopnetclient.frames.clientframetabs;

/**
 *
 * @author subes
 */
public class ConnectingPanel extends javax.swing.JPanel {

    /** Creates new form ConnectingPanel */
    public ConnectingPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_connecting = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lbl_connecting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_connecting.setText("Connecting ...");
        add(lbl_connecting, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_connecting;
    // End of variables declaration//GEN-END:variables

}
