/*	
Copyright 2007  Edwin Stang (edwinstang@gmail.com), 
Kovacs Zsolt (kovacs.zsolt.85@gmail.com)

This file is part of Coopnet.

Coopnet is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Coopnet is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Coopnet.  If not, see <http://www.gnu.org/licenses/>.
 */
package coopnetclient.frames.clientframe.panels;

import coopnetclient.enums.ContactStatuses;
import coopnetclient.frames.clientframe.TabOrganizer;
import coopnetclient.modules.components.ContactListPopupMenu;
import coopnetclient.modules.components.mutablelist.DefaultListCellEditor;
import coopnetclient.modules.models.ContactListModel;
import coopnetclient.modules.renderers.ContactListRenderer;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

public class ContactListPanel extends javax.swing.JPanel {
    
    public static ImageIcon ContactListIcon = new ImageIcon(Toolkit.getDefaultToolkit().getImage("data/icons/quicktab/contacts.png") );//.getScaledInstance(56, 56, Image.SCALE_SMOOTH));
    private static ContactListPopupMenu popup;
    ContactListModel model;
    
    /** Creates new form PlayerListPanel */
    public ContactListPanel() {
        initComponents();
    }

    public ContactListPanel(ContactListModel model) {
        this.model = model;
        initComponents();
        editableJlist1.setModel(model);
        editableJlist1.setCellRenderer(new ContactListRenderer(model));
        editableJlist1.setListCellEditor(new DefaultListCellEditor(new JTextField()));
        popup = new ContactListPopupMenu(editableJlist1);
        editableJlist1.setComponentPopupMenu(popup);
        popup.refreshMoveToMenu();
    }
            
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        editableJlist1 = new coopnetclient.modules.components.mutablelist.EditableJlist();

        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(200, 200));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setFocusable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setMinimumSize(null);

        editableJlist1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        editableJlist1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        editableJlist1.setFocusable(false);
        editableJlist1.setMaximumSize(null);
        editableJlist1.setMinimumSize(null);
        editableJlist1.setPreferredSize(new java.awt.Dimension(150, 200));
        editableJlist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editableJlist1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(editableJlist1);

        jTabbedPane1.addTab("", ContactListIcon, jScrollPane1, "Contact List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void editableJlist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editableJlist1MouseClicked
    if(evt.getClickCount() ==2){
        String selected = editableJlist1.getSelectedValue().toString();
        if(model.getGroupNames().contains(selected)){
            model.toggleGroupClosedStatus(selected);
        }else{
            if(model.getStatus(selected) != ContactStatuses.OFFLINE  ){
                TabOrganizer.openPrivateChatPanel(selected, true);
            }
        }
    }
}//GEN-LAST:event_editableJlist1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private coopnetclient.modules.components.mutablelist.EditableJlist editableJlist1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
