package coopnetclient.frames.components;

import coopnetclient.utils.Logger;
import javax.swing.SwingUtilities;

public class ConnectingProgressBar extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public ConnectingProgressBar() {
        initComponents();
        progressbar.setMinimum(0);
        progressbar.setStringPainted(true);
    }

    public void setProgress(final int cur, final int max){
         SwingUtilities.invokeLater(new Thread() {
            @Override
            public void run() {
                try{
                    progressbar.setMaximum(max);
                    progressbar.setValue(cur);
                    progressbar.setMaximum(max); //Need to do again to be sure it updates
                    progressbar.setString("retry "+progressbar.getValue()+"/"+progressbar.getMaximum());
                    progressbar.repaint();
                }catch(Exception e){
                    Logger.log(e);
                }
            }
        });
    }

    public void setDone(){
        progressbar.setValue(progressbar.getMaximum());
        progressbar.setString("Host found!");
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_connecting = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridLayout(2, 1));

        lbl_connecting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_connecting.setText("Searching for host ...");
        add(lbl_connecting);
        add(progressbar);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_connecting;
    private javax.swing.JProgressBar progressbar;
    // End of variables declaration//GEN-END:variables

}
