/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabComponent.java
 *
 * Created on 2008.12.19., 20:32:42
 */

package coopnetclient.frames.components;

import coopnetclient.utils.Icons;
import javax.swing.Icon;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class TabComponent extends javax.swing.JPanel {

    /** Creates new form TabComponent */
    public TabComponent() {
        initComponents();
        putClientProperty("html.disable", Boolean.TRUE);
    }


    public TabComponent(String title){
        this();
        lbl_text.setText(title);
    }

    public TabComponent(String title, Icon icon){
        this(title);
        lbl_text.setIcon(icon);
        lbl_text.setHorizontalTextPosition(JLabel.RIGHT);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbl_text = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();

        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(45, 25));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lbl_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text.setText("text");
        lbl_text.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(lbl_text, gridBagConstraints);

        btn_close.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_close.setIcon(Icons.tabCloseIconNormal);
        btn_close.setFocusable(false);
        btn_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_close.setMaximumSize(new java.awt.Dimension(20, 20));
        btn_close.setMinimumSize(new java.awt.Dimension(20, 20));
        btn_close.setOpaque(false);
        btn_close.setPreferredSize(new java.awt.Dimension(20, 20));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(btn_close, gridBagConstraints);
        btn_close.getAccessibleContext().setAccessibleName("Close");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        btn_close.setIcon(Icons.tabCloseIconMouseOver);
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        btn_close.setIcon(Icons.tabCloseIconNormal);
    }//GEN-LAST:event_btn_closeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel lbl_text;
    // End of variables declaration//GEN-END:variables

}
