/*	Copyright 2007  Edwin Stang (edwinstang@gmail.com),
 *                  Kovacs Zsolt (kovacs.zsolt.85@gmail.com)
 *
 *  This file is part of Coopnet.
 *
 *  Coopnet is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Coopnet is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Coopnet.  If not, see <http://www.gnu.org/licenses/>.
 */

package coopnetclient.frames.components;

import coopnetclient.frames.clientframe.ClosableTab;
import coopnetclient.utils.Icons;
import javax.swing.Icon;
import javax.swing.JLabel;

public class TabComponent extends javax.swing.JPanel {

    ClosableTab closeMe;

    /** Creates new form TabComponent */
    public TabComponent(ClosableTab closeMe) {
        initComponents();
        putClientProperty("html.disable", Boolean.TRUE);
        lbl_text.setHorizontalTextPosition(JLabel.RIGHT);
        this.closeMe = closeMe;
    }


    public TabComponent(String title,ClosableTab closeMe){
        this(closeMe);
        lbl_text.setText(title);
    }

    public TabComponent(String title, Icon icon,ClosableTab closeMe){
        this(title,closeMe);
        lbl_text.setIcon(icon);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbl_text = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();

        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(45, 25));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lbl_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_text.setText("text");
        lbl_text.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(lbl_text, gridBagConstraints);

        btn_close.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_close.setIcon(Icons.tabCloseIconNormal);
        btn_close.setFocusable(false);
        btn_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_close.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btn_close.setMaximumSize(new java.awt.Dimension(20, 20));
        btn_close.setMinimumSize(new java.awt.Dimension(20, 20));
        btn_close.setOpaque(false);
        btn_close.setPreferredSize(new java.awt.Dimension(20, 20));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(btn_close, gridBagConstraints);
        btn_close.getAccessibleContext().setAccessibleName("Close");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        btn_close.setIcon(Icons.tabCloseIconMouseOver);
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        btn_close.setIcon(Icons.tabCloseIconNormal);
    }//GEN-LAST:event_btn_closeMouseExited

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        closeMe.closeTab();
    }//GEN-LAST:event_btn_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel lbl_text;
    // End of variables declaration//GEN-END:variables

}
