/*	Copyright 2007  Edwin Stang (edwinstang@gmail.com),
 *                  Kovacs Zsolt (kovacs.zsolt.85@gmail.com)
 *
 *  This file is part of Coopnet.
 *
 *  Coopnet is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Coopnet is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Coopnet.  If not, see <http://www.gnu.org/licenses/>.
 */
package coopnetclient.frames.clientframe.tabs;

import coopnetclient.utils.Settings;
import coopnetclient.utils.gamedatabase.GameDatabase;
import java.util.Enumeration;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.TreeSelectionModel;

public class EventsPanel extends javax.swing.JPanel {

    private DefaultMutableTreeNode root = new DefaultMutableTreeNode("Event browser");
    private DefaultMutableTreeNode favsNode = new DefaultMutableTreeNode("Favourites");
    private DefaultMutableTreeNode installedNode = new DefaultMutableTreeNode("Installed Games");
    private DefaultMutableTreeNode allGamesNode = new DefaultMutableTreeNode("All Games");
    private Long currentlyDisplayedEventID = null;

    private static class EventNode extends DefaultMutableTreeNode {

        private Long ID;

        public EventNode(Long ID, String title) {
            super(title);
            this.ID = ID;
        }

        public Long getID() {
            return ID;
        }
    }

    /** Creates new form EventsPanel */
    public EventsPanel() {
        initComponents();
        initNodes();
        tr_games.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tr_games.setShowsRootHandles(true);
        DefaultTreeCellRenderer renderer = new DefaultTreeCellRenderer();
        //custom icons possible
        renderer.setLeafIcon(null);
        renderer.setClosedIcon(null);
        renderer.setOpenIcon(null);
        tr_games.setCellRenderer(renderer);
        tr_games.putClientProperty("JTree.lineStyle", "Angled");//None for no lines
    }

    private void initNodes() {
        root.removeAllChildren();
        root.add(favsNode);
        root.add(installedNode);
        root.add(allGamesNode);
        updateFavouritesNode();
        allGamesNode.removeAllChildren();
        for (String gameName : GameDatabase.getAllGameNamesAsStringArray()) {
            allGamesNode.add(new DefaultMutableTreeNode(gameName));
        }
        installedNode.removeAllChildren();
        for (String gameName : GameDatabase.getInstalledGameNames()) {
            installedNode.add(new DefaultMutableTreeNode(gameName));
        }
    }

    public synchronized void updateFavouritesNode() {
        favsNode.removeAllChildren();
        for (String gameName : Settings.getFavouritesByName()) {
            favsNode.add(new DefaultMutableTreeNode(gameName));
        }
    }

    public void addEvent(String gameName, Long eventID, String eventTitle) {
        EventNode newEvent = new EventNode(eventID, eventTitle);
        Enumeration e = installedNode.children();
        while (e.hasMoreElements()) {
            Object o = e.nextElement();
            if (o instanceof EventNode) {
                EventNode oldEvent = (EventNode) o;
                if (oldEvent.getID().equals(eventID)) {
                    installedNode.remove(oldEvent);
                    installedNode.add(newEvent);
                }
            }
        }
        e = favsNode.children();
        while (e.hasMoreElements()) {
            Object o = e.nextElement();
            if (o instanceof EventNode) {
                EventNode oldEvent = (EventNode) o;
                if (oldEvent.getID().equals(eventID)) {
                    favsNode.remove(oldEvent);
                    favsNode.add(newEvent);
                }
            }
        }
        e = allGamesNode.children();
        while (e.hasMoreElements()) {
            Object o = e.nextElement();
            if (o instanceof EventNode) {
                EventNode oldEvent = (EventNode) o;
                if (oldEvent.getID().equals(eventID)) {
                    allGamesNode.remove(oldEvent);
                    allGamesNode.add(newEvent);
                }
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbl_description = new javax.swing.JLabel();
        sp_games = new javax.swing.JScrollPane();
        tr_games = new JTree(root);
        btn_post = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_signUp = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_description = new javax.swing.JTextArea();
        sp_users = new javax.swing.JScrollPane();
        lst_users = new javax.swing.JList();
        lbl_comments = new javax.swing.JLabel();
        sp_comments = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        lbl_users = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tp_postComment = new javax.swing.JTextPane();

        setLayout(new java.awt.GridBagLayout());

        lbl_description.setText("Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lbl_description, gridBagConstraints);

        sp_games.setViewportView(tr_games);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        add(sp_games, gridBagConstraints);

        btn_post.setText("Post new");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btn_post, gridBagConstraints);

        btn_edit.setText("Edit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btn_edit, gridBagConstraints);

        btn_signUp.setText("Participate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btn_signUp, gridBagConstraints);

        btn_refresh.setText("Refresh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btn_refresh, gridBagConstraints);

        ta_description.setColumns(20);
        ta_description.setRows(5);
        jScrollPane1.setViewportView(ta_description);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        lst_users.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lst_users.setMaximumSize(null);
        lst_users.setMinimumSize(null);
        lst_users.setPreferredSize(null);
        sp_users.setViewportView(lst_users);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(sp_users, gridBagConstraints);

        lbl_comments.setText("Comments:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lbl_comments, gridBagConstraints);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "comment 1", "comment 2", "comment 3", "comment 4", "comment 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        sp_comments.setViewportView(jList2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 4);
        add(sp_comments, gridBagConstraints);

        lbl_users.setText("Participants:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lbl_users, gridBagConstraints);

        tp_postComment.setText("<Your comment here>");
        jScrollPane2.setViewportView(tp_postComment);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_post;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_signUp;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_comments;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_users;
    private javax.swing.JList lst_users;
    private javax.swing.JScrollPane sp_comments;
    private javax.swing.JScrollPane sp_games;
    private javax.swing.JScrollPane sp_users;
    private javax.swing.JTextArea ta_description;
    private javax.swing.JTextPane tp_postComment;
    private javax.swing.JTree tr_games;
    // End of variables declaration//GEN-END:variables
}
