/*	Copyright 2007  Edwin Stang (edwinstang@gmail.com), 
 *                  Kovacs Zsolt (kovacs.zsolt.85@gmail.com)
 *
 *  This file is part of Coopnet.
 *
 *  Coopnet is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Coopnet is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Coopnet.  If not, see <http://www.gnu.org/licenses/>.
 */

package coopnetclient.frames.clientframe.tabs;

import coopnetclient.Globals;
import coopnetclient.frames.clientframe.TabOrganizer;
import coopnetclient.protocol.out.Protocol;
import coopnetclient.utils.Verification;
import javax.swing.JOptionPane;

public class PasswordRecoveryPanel extends javax.swing.JPanel {

    /** Creates new form LoginPanel */
    public PasswordRecoveryPanel() {
        initComponents();
        tf_name.setText(coopnetclient.utils.Settings.getLastLoginName());
        coopnetclient.utils.Colorizer.colorize(this);
    }

    @Override
    public void requestFocus() {
         tf_name.requestFocus();        
    }


    private void recovery() {
        String name = tf_name.getText();
        String email = tf_email.getText();

        if(!Verification.verifyLoginName(name)){
            tf_name.showErrorMessage("Invalid login name!");
            return;
        }
        
        if(!Verification.verifyEMail(email)){
            tf_email.showErrorMessage("Invalid email adress!");
            return;
        }
        
        TabOrganizer.closePasswordRecoveryPanel();
        TabOrganizer.openLoginPanel();
        Protocol.passwordRecovery(name,email);
        JOptionPane.showMessageDialog(Globals.getClientFrame(), "<html><b>Request sent!</b>\n" +
                            "If the data is valid you will receive an E-Mail with your new password shortly!", "Request sent", JOptionPane.INFORMATION_MESSAGE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_input = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        btn_send = new javax.swing.JButton();
        lbl_Info = new javax.swing.JLabel();
        tf_name = new coopnetclient.frames.components.AdvancedJTextField();
        tf_email = new coopnetclient.frames.components.AdvancedJTextField();
        btn_cancel = new javax.swing.JButton();

        setFocusable(false);
        setLayout(new java.awt.GridBagLayout());

        pnl_input.setBorder(javax.swing.BorderFactory.createTitledBorder("Password recovery"));
        pnl_input.setFocusable(false);

        lbl_name.setText("Name:");
        lbl_name.setFocusable(false);

        lbl_email.setText("E-Mail:");
        lbl_email.setFocusable(false);

        btn_send.setText("Send");
        btn_send.setNextFocusableComponent(tf_name);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        lbl_Info.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Info.setText("<html>Please fill in your account information.<br>Your new password will be sent via E-Mail.");
        lbl_Info.setFocusable(false);

        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });

        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_inputLayout = new javax.swing.GroupLayout(pnl_input);
        pnl_input.setLayout(pnl_inputLayout);
        pnl_inputLayout.setHorizontalGroup(
            pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_inputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Info, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addGroup(pnl_inputLayout.createSequentialGroup()
                        .addComponent(btn_send)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addComponent(btn_cancel))
                    .addGroup(pnl_inputLayout.createSequentialGroup()
                        .addGroup(pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name)
                            .addComponent(lbl_email))
                        .addGap(10, 10, 10)
                        .addGroup(pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_email, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(tf_name, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnl_inputLayout.setVerticalGroup(
            pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_inputLayout.createSequentialGroup()
                .addComponent(lbl_Info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_inputLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_name))
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_send)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        add(pnl_input, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        btn_send.doClick();
    }//GEN-LAST:event_tf_nameActionPerformed

private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
    btn_send.doClick();
}//GEN-LAST:event_tf_emailActionPerformed

private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
     recovery();     
}//GEN-LAST:event_btn_sendActionPerformed

private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
    TabOrganizer.closePasswordRecoveryPanel();
    TabOrganizer.openLoginPanel();
}//GEN-LAST:event_btn_cancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_send;
    private javax.swing.JLabel lbl_Info;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JPanel pnl_input;
    private coopnetclient.frames.components.AdvancedJTextField tf_email;
    private coopnetclient.frames.components.AdvancedJTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
