/*	Copyright 2007  Edwin Stang (edwinstang@gmail.com), 
 *                  Kovacs Zsolt (kovacs.zsolt.85@gmail.com)
 *
 *  This file is part of Coopnet.
 *
 *  Coopnet is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Coopnet is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Coopnet.  If not, see <http://www.gnu.org/licenses/>.
 */

package coopnetclient.frames.clientframe.tabs;

import coopnetclient.Globals;
import coopnetclient.frames.clientframe.TabOrganizer;
import coopnetclient.protocol.out.Protocol;
import coopnetclient.utils.Verification;
import javax.swing.JOptionPane;

public class PasswordRecoveryPanel extends javax.swing.JPanel {

    /** Creates new form LoginPanel */
    public PasswordRecoveryPanel() {
        initComponents();
        tf_name.setText(coopnetclient.utils.Settings.getLastLoginName());
        coopnetclient.utils.Colorizer.colorize(this);
    }

    @Override
    public void requestFocus() {
        tf_name.requestFocus();
    }


    private void recovery() {
        String name = tf_name.getText();
        String email = tf_email.getText();

        if(!Verification.verifyLoginName(name)){
            tf_name.showErrorMessage("Invalid login name!");
            return;
        }
        
        if(!Verification.verifyEMail(email)){
            tf_email.showErrorMessage("Invalid email adress!");
            return;
        }
        
        Protocol.passwordRecovery(name,email);
        JOptionPane.showMessageDialog(Globals.getClientFrame(), "<html><b>Request sent!</b>\n" +
                            "If the data is valid you will revieve an email with your new password shortly!", "Request sent", JOptionPane.INFORMATION_MESSAGE);
                    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_top = new javax.swing.JPanel();
        pnl_input = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        btn_send = new javax.swing.JButton();
        lbl_Info = new javax.swing.JLabel();
        tf_name = new coopnetclient.frames.components.AdvancedJTextField();
        tf_email = new coopnetclient.frames.components.AdvancedJTextField();
        btn_cancel = new javax.swing.JButton();
        pnl_bottom = new javax.swing.JPanel();
        lbl_info = new javax.swing.JLabel();

        setFocusable(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnl_top.setFocusable(false);
        pnl_top.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout pnl_topLayout = new javax.swing.GroupLayout(pnl_top);
        pnl_top.setLayout(pnl_topLayout);
        pnl_topLayout.setHorizontalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );
        pnl_topLayout.setVerticalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        add(pnl_top);

        pnl_input.setBorder(javax.swing.BorderFactory.createTitledBorder("Password Recovery"));
        pnl_input.setFocusable(false);
        pnl_input.setMaximumSize(new java.awt.Dimension(300, 300));
        pnl_input.setMinimumSize(new java.awt.Dimension(300, 170));
        pnl_input.setPreferredSize(new java.awt.Dimension(300, 170));
        pnl_input.setLayout(new java.awt.GridBagLayout());

        lbl_name.setText("Name:");
        lbl_name.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnl_input.add(lbl_name, gridBagConstraints);

        lbl_email.setText("Email:");
        lbl_email.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnl_input.add(lbl_email, gridBagConstraints);

        btn_send.setText("Send");
        btn_send.setNextFocusableComponent(tf_name);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        pnl_input.add(btn_send, gridBagConstraints);

        lbl_Info.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Info.setText("<html>Please fill in your account information!<br>Your new password will be sent via email!");
        lbl_Info.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnl_input.add(lbl_Info, gridBagConstraints);

        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(tf_name, gridBagConstraints);

        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(tf_email, gridBagConstraints);

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(btn_cancel, gridBagConstraints);

        add(pnl_input);

        pnl_bottom.setFocusable(false);
        pnl_bottom.setPreferredSize(new java.awt.Dimension(10, 10));

        lbl_info.setFont(new java.awt.Font("Tahoma", 0, 10));
        lbl_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_info.setText("<html><pre> <br> <br>");
        lbl_info.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_info.setFocusable(false);

        javax.swing.GroupLayout pnl_bottomLayout = new javax.swing.GroupLayout(pnl_bottom);
        pnl_bottom.setLayout(pnl_bottomLayout);
        pnl_bottomLayout.setHorizontalGroup(
            pnl_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_info, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        pnl_bottomLayout.setVerticalGroup(
            pnl_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bottomLayout.createSequentialGroup()
                .addComponent(lbl_info)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(pnl_bottom);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        btn_send.doClick();
    }//GEN-LAST:event_tf_nameActionPerformed

private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
    btn_send.doClick();
}//GEN-LAST:event_tf_emailActionPerformed

private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
     recovery();
     TabOrganizer.closePasswordRecoveryPanel();
     TabOrganizer.openLoginPanel();
}//GEN-LAST:event_btn_sendActionPerformed

private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
    TabOrganizer.closePasswordRecoveryPanel();
    TabOrganizer.openLoginPanel();
}//GEN-LAST:event_btn_cancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_send;
    private javax.swing.JLabel lbl_Info;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_info;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JPanel pnl_bottom;
    private javax.swing.JPanel pnl_input;
    private javax.swing.JPanel pnl_top;
    private coopnetclient.frames.components.AdvancedJTextField tf_email;
    private coopnetclient.frames.components.AdvancedJTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
