/*	Copyright 2007  Edwin Stang (edwinstang@gmail.com), 
 *                  Kovacs Zsolt (kovacs.zsolt.85@gmail.com)
 *
 *  This file is part of Coopnet.
 *
 *  Coopnet is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Coopnet is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Coopnet.  If not, see <http://www.gnu.org/licenses/>.
 */

package coopnetclient.frames.clientframe.tabs;

import coopnetclient.frames.clientframe.TabOrganizer;
import coopnetclient.protocol.out.Protocol;
import coopnetclient.utils.Verification;
import java.awt.Color;

public class RegisterPanel extends javax.swing.JPanel {

    /** Creates new form LoginPanel */
    public RegisterPanel() {
        initComponents();
        lbl_Info.setVisible(true);
        coopnetclient.utils.Colorizer.colorize(this);
    }

    @Override
    public void requestFocus() {
        tf_name.requestFocus();
    }

    private void register() {
        String name = tf_name.getText();        
        String password1 = new String(pf_password1.getPassword());
        String password2 = new String(pf_password2.getPassword());
        String email = tf_email.getText();
        String ingameName = tf_ingameName.getText();
        String country = cmb_country.getSelectedItem().toString();
        String website = tf_website.getText();

        boolean error = false;
        
        if(!Verification.verifyLoginName(name)){
            tf_name.showErrorMessage("Invalid login name!");
            error = true;
        }
        
        if(!Verification.verifyEMail(email)){
            tf_email.showErrorMessage("Invalid email adress!");
            error = true;
        }
        
        if(ingameName.length()>0 && !Verification.verifyIngameName(ingameName)){
            tf_ingameName.showErrorMessage("Invalid name!");
            error = true;
        }
        
        if(!Verification.verifyWebsite(website)){
            tf_website.showErrorMessage("Invalid website!");
            error = true;
        } 
        
        if(!Verification.verifyPassword(password1)){
            lbl_error.setForeground(Color.red);
            lbl_error.setText("Invalid password!");
            pf_password1.setText("");
            pf_password2.setText("");
            error = true;
        } else        
        if(!password1.equals(password2)){
            lbl_error.setForeground(Color.red);
            lbl_error.setText("Passwords dont match!");
            error = true;
        }else{
            lbl_error.setText(" ");
        }
        
        if(!error){            
            Protocol.register(name,password1,email,ingameName,(cmb_country.getSelectedIndex() == 0) ? "" : cmb_country.getSelectedItem().toString(),website);
            coopnetclient.utils.Settings.setLastLoginName(name);
        }
    }
    
    public void showLoginNameUsedError(){
        tf_name.showErrorMessage("Name is already in use!");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnl_top = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnl_input = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        btn_send = new javax.swing.JButton();
        lbl_Info = new javax.swing.JLabel();
        tf_name = new coopnetclient.frames.components.AdvancedJTextField();
        tf_email = new coopnetclient.frames.components.AdvancedJTextField();
        lbl_ingameName = new javax.swing.JLabel();
        tf_ingameName = new coopnetclient.frames.components.AdvancedJTextField();
        lbl_password1 = new javax.swing.JLabel();
        lbl_password2 = new javax.swing.JLabel();
        pf_password1 = new javax.swing.JPasswordField();
        pf_password2 = new javax.swing.JPasswordField();
        lbl_country = new javax.swing.JLabel();
        cmb_country = new javax.swing.JComboBox();
        lbl_website = new javax.swing.JLabel();
        tf_website = new coopnetclient.frames.components.AdvancedJTextField();
        lbl_error = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        pnl_bottom = new javax.swing.JPanel();
        lbl_info = new javax.swing.JLabel();

        setFocusable(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        pnl_top.setFocusable(false);
        pnl_top.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout pnl_topLayout = new javax.swing.GroupLayout(pnl_top);
        pnl_top.setLayout(pnl_topLayout);
        pnl_topLayout.setHorizontalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        pnl_topLayout.setVerticalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        add(pnl_top);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registration"));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(340, 340));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 340));

        pnl_input.setFocusable(false);
        pnl_input.setMaximumSize(new java.awt.Dimension(300, 300));
        pnl_input.setMinimumSize(new java.awt.Dimension(300, 300));
        pnl_input.setPreferredSize(new java.awt.Dimension(300, 300));
        pnl_input.setLayout(new java.awt.GridBagLayout());

        lbl_name.setText("Login name*");
        lbl_name.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnl_input.add(lbl_name, gridBagConstraints);

        lbl_email.setText("Email*");
        lbl_email.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnl_input.add(lbl_email, gridBagConstraints);

        btn_send.setText("Register");
        btn_send.setNextFocusableComponent(tf_name);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        pnl_input.add(btn_send, gridBagConstraints);

        lbl_Info.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Info.setText("<html>Please fill in your account information!<br>Fields marked by * are required");
        lbl_Info.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 1, 5);
        pnl_input.add(lbl_Info, gridBagConstraints);

        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(tf_name, gridBagConstraints);

        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(tf_email, gridBagConstraints);

        lbl_ingameName.setText("In-game name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnl_input.add(lbl_ingameName, gridBagConstraints);

        tf_ingameName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ingameNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(tf_ingameName, gridBagConstraints);

        lbl_password1.setText("Password*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnl_input.add(lbl_password1, gridBagConstraints);

        lbl_password2.setText("Password again*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnl_input.add(lbl_password2, gridBagConstraints);

        pf_password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_password1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(pf_password1, gridBagConstraints);

        pf_password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_password2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(pf_password2, gridBagConstraints);

        lbl_country.setText("Country:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnl_input.add(lbl_country, gridBagConstraints);

        cmb_country.setModel(new javax.swing.DefaultComboBoxModel(CountryList));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(cmb_country, gridBagConstraints);

        lbl_website.setText("Website:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 10);
        pnl_input.add(lbl_website, gridBagConstraints);

        tf_website.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_websiteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        pnl_input.add(tf_website, gridBagConstraints);

        lbl_error.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        pnl_input.add(lbl_error, gridBagConstraints);

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnl_input.add(btn_cancel, gridBagConstraints);

        jScrollPane1.setViewportView(pnl_input);

        add(jScrollPane1);

        pnl_bottom.setFocusable(false);
        pnl_bottom.setPreferredSize(new java.awt.Dimension(10, 10));

        lbl_info.setFont(new java.awt.Font("Tahoma", 0, 10));
        lbl_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_info.setText("<html><pre> <br> <br>");
        lbl_info.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_info.setFocusable(false);

        javax.swing.GroupLayout pnl_bottomLayout = new javax.swing.GroupLayout(pnl_bottom);
        pnl_bottom.setLayout(pnl_bottomLayout);
        pnl_bottomLayout.setHorizontalGroup(
            pnl_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_info, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        pnl_bottomLayout.setVerticalGroup(
            pnl_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bottomLayout.createSequentialGroup()
                .addComponent(lbl_info)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(pnl_bottom);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        btn_send.doClick();
    }//GEN-LAST:event_tf_nameActionPerformed

private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
    btn_send.doClick();
}//GEN-LAST:event_tf_emailActionPerformed

private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
     register();
}//GEN-LAST:event_btn_sendActionPerformed

private void tf_ingameNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ingameNameActionPerformed
    btn_send.doClick();
}//GEN-LAST:event_tf_ingameNameActionPerformed

private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
    TabOrganizer.closeRegisterPanel();
    TabOrganizer.openLoginPanel();
}//GEN-LAST:event_btn_cancelActionPerformed

private void pf_password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_password1ActionPerformed
    btn_send.doClick();
}//GEN-LAST:event_pf_password1ActionPerformed

private void pf_password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_password2ActionPerformed
    btn_send.doClick();
}//GEN-LAST:event_pf_password2ActionPerformed

private void tf_websiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_websiteActionPerformed
    btn_send.doClick();
}//GEN-LAST:event_tf_websiteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_send;
    private javax.swing.JComboBox cmb_country;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Info;
    private javax.swing.JLabel lbl_country;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_info;
    private javax.swing.JLabel lbl_ingameName;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password1;
    private javax.swing.JLabel lbl_password2;
    private javax.swing.JLabel lbl_website;
    private javax.swing.JPasswordField pf_password1;
    private javax.swing.JPasswordField pf_password2;
    private javax.swing.JPanel pnl_bottom;
    private javax.swing.JPanel pnl_input;
    private javax.swing.JPanel pnl_top;
    private coopnetclient.frames.components.AdvancedJTextField tf_email;
    private coopnetclient.frames.components.AdvancedJTextField tf_ingameName;
    private coopnetclient.frames.components.AdvancedJTextField tf_name;
    private coopnetclient.frames.components.AdvancedJTextField tf_website;
    // End of variables declaration//GEN-END:variables
    public static String[] CountryList = new String[]{"Select your country", "Abkhazia", "Afghanistan", "Akrotiri and Dhekelia", "Ĺland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla",
        "Antigua and Barbuda", "Argentina ", "Armenia ", "Aruba", "Ascension Island",
        "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
        "Belarus", "Belgium", "Belize", "Benin ", "Bermuda", "Bhutan", "Bolivia", " Bosnia", "Botswana", "Brazil",
        "Brunei", " Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde",
        "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "ChristmasIsland",
        "Cocos", "Colombia", "Comoros", "Congo", "Cook Islands", "Costa Rica", "Côte d'Ivoire",
        "Croatia", "Cuba", "Cyprus", "Czech", "Denmark", "Djibouti", "Dominica", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands",
        "Faroe Islands", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany",
        "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guam", "Guatemala", "Guernsey", "Guinea",
        "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia",
        "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey",
        "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia",
        "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao",
        "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands",
        "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia",
        "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Nagorno-Karabakh", "Namibia", "Nauru",
        "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island",
        "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru",
        "Philippines", "Pitcairn", "Poland", "Portugal", "Pridnestrovie", "Puerto Rico", "Qatar",
        "Romania", "Russia", "Rwanda", "Saint-Barthélemy", "Saint Helena", "Saint Kitts and Nevis",
        "Saint Lucia", "Saint Martin", "Saint-Pierre and	Miquelon",
        "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Săo Tomé and Príncipe",
        "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia",
        "Slovenia", "Solomon	Islands", "Somalia", "Somaliland", "South Africa", "South Ossetia",
        "Spain", "SriLanka", "Sudan", "Suriname", "Svalbard", "Swaziland", "Sweden",
        "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor",
        "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tristan da Cunha",
        "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos", "Tuvalu", "Uganda",
        "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
        "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam",
        "Virgin Islands", "Wallis and Futuna", "Western Sahara", "Yemen",
        "Zambia", "Zimbabwe"
    };
}
